language: php
sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/symfony-bridge/.phpunit

env:
  global:
    - SYMFONY_PHPUNIT_DIR="$HOME/symfony-bridge/.phpunit"

matrix:
  fast_finish: true
  include:
    # We don't use 7.1 because of this issue https://github.com/travis-ci/travis-ci/issues/6339
    - php: 7.1.18
    - php: 7.2
    - php: nightly
  allow_failures:
    - php: nightly

before_install:
  - '[[ "$TRAVIS_PHP_VERSION" == "nightly" ]] || phpenv config-rm xdebug.ini'
  - composer self-update
  - mysql -e 'CREATE DATABASE bull;'

script:
  - make ci